# Jobs to run on PR, tests, lint, check, etc.
name: Default branch verification

on:
  push:
    branches:
      - add-ci

jobs:

  test-default:
    name: Publish snapshot
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-default
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 15

#        TODO add tests, test-coverage and uncomment the blocks
#        @SEE https://github.dev/artemkaxboy/SpringDataShowroom/tree/master/.github/workflows
#      - name: Run check
        # @doc https://github.com/eskatos/gradle-command-action
#        uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: check jacocoTestReport

#      - uses: actions/upload-artifact@v2
#        with:
#          name: test-result
#          path: ./build/reports/tests/test/
#        if: always()

#      - name: Upload coverage result
#        env:
#          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
#        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report

      - name: Set RELEASE_VERSION variable
        run: echo "ORG_GRADLE_PROJECT_applicationVersion=SNAPSHOT" >> $GITHUB_ENV

      - name: Publish dockerhub
        uses: eskatos/gradle-command-action@v1
        env:
          CONTAINER_REGISTRY_USERNAME: ${{ github.actor }}
          CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
          CONTAINER_IMAGE_TAG: SNAPSHOT
          CONTAINER_IMAGE: ghcr.io/${{ github.repository }}
        with:
          arguments: |
              jib -Dorg.gradle.console=plain
                  -Djib.to.image='${{ env.CONTAINER_IMAGE }}:${{ env.CONTAINER_IMAGE_TAG }}'
                  -Djib.to.tags='${{ env.CONTAINER_IMAGE_TAG }}'

#      - name: Publish dockerhub
#        uses: eskatos/gradle-command-action@v1
#        env:
#          CONTAINER_REGISTRY_USERNAME: ${{ github.actor }}
#          CONTAINER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
#        with:
#          arguments: jib -Dorg.gradle.console=plain
