# Jobs to run on PR, tests, lint, check, etc.
name: Check PR

on:
  pull_request:
    branches:
      - main

jobs:

  test-and-measure-coverage:

    name: Test and measure coverage
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-default
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 15

        # @SEE https://github.dev/artemkaxboy/SpringDataShowroom/tree/master/.github/workflows
      - name: Run check
        # @doc https://github.com/eskatos/gradle-command-action
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check jacocoTestReport

      - uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: ./build/reports/tests/test/
        if: always()

      - name: Upload coverage result
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report
